#sentinel cluster single
redis:
  cluster: single
  #redis节点id
  nodes: 127.0.0.1:6379
#redis.database=0
#redis.password=
#是否开启key的多节点冗余
server:
  enable:
    redundant: false
    health-report: false
    # 只有在Health-report为true的时候才有效
    delay: 3
  bindPort: 6067
  workThread: 30
  bossThread: 10
  groupId: 1
  registerAddress: zookeeper:127.0.0.1:2181
