#sentinel cluster single
redis:
  cluster: single
  #redis节点id
  nodes: 47.97.215.217:6061
#redis.database=0
#redis.password=
#是否开启key的多节点冗余
server:
  enable:
    redundant: false
    health-report: true
    # 只有在Health-report为true的时候才有效
    delay: 3
  bindPort: 6067
  workThread: 10
  bossThread: 10
  groupId: 1
  registerAddress: zookeeper:47.97.215.217:2181
