#sentinel cluster single
redis:
  cluster: single
  #redis节点id
  nodes: 127.0.0.1:6063
#redis.database=0
#redis.password=
#是否开启key的多节点冗余
server:
  enable:
    redundant: false
  bindPort: 6063
  workThread: 5
  groupId: 2
  #registerAddress: zookeeper:4127.0.0.1:2181,127.0.0.1:2182
  registerAddress: zookeeper:127.0.0.1:2181
