#sentinel cluster single
redis:
  cluster: single
  #redis节点id
  nodes: 127.0.0.1:6061
#redis.database=0
#redis.password=
#是否开启key的多节点冗余
server:
  enable:
    redundant: false
    health-report: true
  bindPort: 6067
  workThread: 10
  bossThread: 10
  groupId: 2
  registerAddress: zookeeper:127.0.0.1:2181
