panda:
  redis:
    max-active: 2
    min-idle: 0
    max-idle: 20
    max-wait: -1
    groupClients:
      - groupClient:
          nodes:
            - 127.0.0.1:6061
            - 127.0.0.1:6062
          clientLoadBalance: roundRobinClientLoadBalance
      - groupClient:
          nodes:
            - 127.0.0.1:6061
            - 127.0.0.1:6062
server:
  port: 8080
