panda:
  redis:
    max-active: 2
    min-idle: 0
    max-idle: 20
    max-wait: -1
    groupLoadBalance: com.panda.redis.core.loadBalance.impl.KeyHashLoadBalance
    group-proxies[0]:
      nodes[0]: 127.0.0.1:6061
      nodes[1]: 127.0.0.1:6062
      #proxy节点间负载均衡策略
      proxy-load-balance: com.panda.redis.core.loadBalance.impl.RoundRobinClientLoadBalance
    group-proxies[1]:
      nodes[0]: 127.0.0.1:6063
server:
  port: 8080
